---
title: "NCAA top athletes in each event from 2010 to 2021"
author: "TS O'Leary"
output:
  rmarkdown::html_document:
    theme: sandstone
    toc: false
    toc_float: false
runtime: shiny
---

```{r setup, include = FALSE}
# don't show cose, warnings or messages
knitr::opts_chunk$set(echo = FALSE, 
                      warning = FALSE, 
                      message = FALSE)

# Load packages
require(tidyverse)
require(shiny)
require(broom)

shinyThings::radioSwitchButtons_default_style(selected_background = "#faa555")

# Load data
df <- readRDS(url("https://tsoleary.github.io/track/NCAA/data/tfrrs_NCAA_2010_2021_final_data_team.rds"))

# Create split data by event type -- TRACK, FIELD, MULTI -- for analysis
df_split <- df %>%
  group_by(EVENT_TYPE) %>%
  group_split()

# Colors for plotting teams
df_colors <- read_csv("https://raw.githubusercontent.com/tsoleary/track/main/NCAA/data/ncaa_colors.csv")


# Define sprint events for plotting
sprints <- unique(df$EVENT)[c(1:3, 9:12)]

# Define functions ----
# Function: violin_box_plot -----
# Description: Creates a violin box plot
# Inputs: input_description
# Outputs: output_description

# Required packages
require(tidyverse)

# Example call
# df %>%
#   filter(EVENT == "Long Jump" & SEX == "Men") %>%
#   violin_box_plot(y = "MARK_METERS", y_lab = "Meters")


violin_box_plot <- function(dat, 
                            y,
                            x_lab = "", 
                            y_lab = y) {
  ggplot(dat,
         aes_string(x = "YEAR_QUAL", 
                    y = y)) +
    geom_violin(fill = "azure2", 
                color = "grey40") +
    geom_boxplot(fill = "azure2", 
                 color = "grey40", 
                 width = 0.2) +
    labs(x = x_lab, y = y_lab,
         title = paste0(unique(dat$SEX), "'s ", unique(dat$EVENT))) +
    theme_classic(base_size = 16)
} ## End function -----

```

<!-- # Questions to answer with this data -->

<!-- - Fastest versus very fast -- rich get richer... top 500 versus top 50, top 8 -->
<!-- - UVM versus country -->
<!-- - Which events are getting better or staying the same? -->
<!-- - Are women or men improving faster? -->
<!-- - Power conferences versus the country -->
<!-- - Distribution of class year men versus women? over time and event -- are some events younger. are women or men younger? -->
<!-- - which have lopsided year distribution, 5th year transfers versus improvements -->


<!-- - team with the most 1st, top 8's 500's etc -->


```{r shiny}
shinyApp(
  
  # Define the user interface
  ui <- fluidPage(
    
    # titlePanel("Test"),
    
    sidebarLayout(
      
      sidebarPanel(width = 3,
        
        # Choose the Event
        selectInput(
          inputId = "event", 
          label = "Event",
          choices = c(unique(df$EVENT)[1:21], "Multi"), 
          selected = "800m"
          ),
        
        # Choose Sex
        shinyThings::radioSwitchButtons(
          inputId = "sex",
          choices = c("Men" = "Men", "Women" = "Women"),
          selected = "Women"
          ),

        # Choose rank
        sliderInput(
          inputId = "rank",
          label = "Top # Athletes",
          min = 0,
          max = 500,
          value = 100,
          step = 10,
          ),
        
        # Choose team(s) to add to plot
        selectInput(
          inputId = "teams", 
          label = "Teams",
          choices = unique(df$ncaa_name), 
          multiple = TRUE,
          selected = NULL
          ),
        
        ),
      
      # Plot  
      mainPanel(width = 9,
                plotOutput(outputId = "plot"))
    )
  ),
  
  
  # Define the server
  server <- function(input, output, session) {
    
    
    # Filter data based on inputs
    data <- reactive({
      if (input$event == "Multi") {
        if (input$sex == "Men") {
          temp <- df %>% 
            filter(EVENT == "Decathlon" & SEX == input$sex) %>% 
            filter(RANK <= input$rank)
        } else {
          temp <- df %>% 
            filter(EVENT == "Heptathlon" & SEX == input$sex) %>% 
            filter(RANK <= input$rank)
        }
      } else {
          temp <- df %>% 
            filter(EVENT == input$event & SEX == input$sex) %>% 
            filter(RANK <= input$rank)
      }
      
      temp

      })
    
    # Filter data based on inputs
    data_team <- reactive({
      dat <- data()
      
      if (length(input$teams > 0)) {
        temp <- dat %>%
          filter(ncaa_name %in% input$teams)
      } else {
        temp <- NULL
      }
      
      temp

      })
    
        # Filter data based on inputs
    data_team_cols <- reactive({
      
      if (length(input$teams > 0)) {
        temp <- df_colors %>%
          filter(ncaa_name %in% input$teams) %>%
        group_by(ncaa_name) %>%
        group_split()
      } else {
        temp <- NULL
      }
      
      temp

      })
    
    # Plot
    output$plot <- renderPlot({
      temp <- data() 
      
      if (unique(temp$EVENT_TYPE) == "TRACK") {
        if (unique(temp$EVENT) %in% sprints) {
          p <- temp %>%
            violin_box_plot(y = "TIME_S", 
                            y_lab = "Time (sec)")  + 
            scale_y_continuous(labels = scales::label_number(accuracy = 0.01))
        } else {
          p <- temp %>%
            violin_box_plot(y = "TIME_S", 
                            y_lab = "Time (min:sec)") +
            scale_y_time(labels = function(l) strftime(l, '%M:%S'))
        }

      } else if (unique(temp$EVENT_TYPE) == "FIELD") {
          p <- temp %>%
            violin_box_plot(y = "MARK_METERS", 
                            y_lab = "Mark (m)") + 
            scale_y_continuous(labels = scales::label_number(accuracy = 0.01))
        
      } else {
          p <- temp %>%
            violin_box_plot(y = "POINTS", 
                            y_lab = "Points")
        
      }
      
      
      if (length(input$teams) > 0) {
        # Define reactive input
        dat <- data_team()
        cols <- data_team_cols()
        
        # Split data into a list of teams
        dat <- dat %>%
          group_by(ncaa_name) %>%
          group_split()
        
              if (unique(temp$EVENT_TYPE) == "TRACK") {
        if (unique(temp$EVENT) %in% sprints) {
          for (i in 1:length(input$teams)) {
            p <- p +
               geom_jitter(data = dat[[i]], 
                           width = 0.1,
                           aes(x = YEAR_QUAL, 
                               y = TIME_S),
                           alpha = 0.9,
                           size = 2.5, 
                           shape = 21, 
                           stroke = 1,
                           fill = cols[[i]]$primary_color[1],
                           color = cols[[i]]$secondary_color[1])
          }
        } else {
          for (i in 1:length(input$teams)) {
            p <- p +
               geom_jitter(data = dat[[i]], 
                           width = 0.1,
                           aes(x = YEAR_QUAL, 
                               y = TIME_S),
                           alpha = 0.9,
                           size = 2.5, 
                           shape = 21, 
                           stroke = 1,
                           fill = cols[[i]]$primary_color[1],
                           color = cols[[i]]$secondary_color[1])
          }
        }

      } else if (unique(temp$EVENT_TYPE) == "FIELD") {
          for (i in 1:length(input$teams)) {
            p <- p +
               geom_jitter(data = dat[[i]], 
                           width = 0.1,
                           aes(x = YEAR_QUAL, 
                               y = MARK_METERS),
                           alpha = 0.9,
                           size = 2.5, 
                           shape = 21, 
                           stroke = 1,
                           fill = cols[[i]]$primary_color[1],
                           color = cols[[i]]$secondary_color[1])
          }
        
      } else {
          for (i in 1:length(input$teams)) {
            p <- p +
               geom_jitter(data = dat[[i]], 
                           width = 0.1,
                           aes(x = YEAR_QUAL, 
                               y = POINTS),
                           alpha = 0.9,
                           size = 2.5, 
                           shape = 21, 
                           stroke = 1,
                           fill = cols[[i]]$primary_color[1],
                           color = cols[[i]]$secondary_color[1])
          }
        
      }
        
        
      }
      
      p
      

      })
  },

  # Set height for output of panel in html
  options = list(height = 1000)
)
```

```{r}
# ggplot() +
#   geom_violin(data = x[[i]], aes(x = YEAR_QUAL, y = TIME_M),
#               fill = "azure2", color = "grey40") +
#   geom_boxplot(data = x[[i]], aes(x = YEAR_QUAL, y = TIME_M),
#                fill = "azure2", color = "grey40", width = 0.2) +
#   geom_smooth(data = x[[i]], aes(x = as.numeric(YEAR_QUAL), y = TIME_M),
#               method = lm, 
#               se = FALSE,
#               formula = y ~ x, 
#               color = "grey50") +
#     geom_smooth(data = df_uvm, aes(x = as.numeric(YEAR_QUAL), y = TIME_M),
#               method = lm, 
#               se = FALSE,
#               formula = y ~ x, 
#               color = "darkgreen") +
#   geom_jitter(data = df_uvm, 
#               width = 0.1,
#              aes(x = YEAR_QUAL, y = TIME_M),
#              alpha = 0.9,
#              size = 2, 
#              shape = 21, 
#              stroke = 1,
#              color = "darkgreen", 
#              fill = "gold") +
#   labs(title = paste0(unique(x[[i]]$SEX), "'s ", unique(x[[i]]$EVENT))) +
#   theme_classic()
```

<!-- # Regression on the data -->

```{r, eval = FALSE}
# Run linear regressions

# Define top number of athletes
top_n_ath <- 8

# Field events -- linear regression
df_field_lm <- df_split[[1]] %>%
  group_by(EVENT, SEX, YEAR_QUAL) %>%
  slice_min(order_by = RANK,
            n = top_n_ath) %>%
  ungroup(YEAR_QUAL) %>%
  mutate(YEAR_QUAL = as.numeric(as.character(YEAR_QUAL))) %>%
  nest() %>%
  mutate(
    fit = map(data, ~ lm(MARK_METERS ~ YEAR_QUAL, data = .x)),
    tidied = map(fit, tidy),
    glanced = map(fit, glance)
  ) %>%
  unnest(tidied)

# Multi events -- linear regression
df_multi_lm <- df_split[[2]] %>%
  group_by(EVENT, SEX, YEAR_QUAL) %>%
  slice_min(order_by = RANK,
            n = top_n_ath) %>%
  ungroup(YEAR_QUAL) %>%
  mutate(YEAR_QUAL = as.numeric(as.character(YEAR_QUAL))) %>%
  nest() %>%
  mutate(
    fit = map(data, ~ lm(POINTS ~ YEAR_QUAL, data = .x)),
    tidied = map(fit, tidy),
    glanced = map(fit, glance)
  ) %>%
  unnest(tidied)

# Track events -- linear regression
df_track_lm <- df_split[[3]] %>%
  group_by(EVENT, SEX, YEAR_QUAL) %>%
  slice_min(order_by = RANK,
            n = top_n_ath) %>%
  ungroup(YEAR_QUAL) %>%
  mutate(YEAR_QUAL = as.numeric(as.character(YEAR_QUAL))) %>%
  nest() %>%
  mutate(
    fit = map(data, ~ lm(TIME_S ~ YEAR_QUAL, data = .x)),
    tidied = map(fit, tidy),
    glanced = map(fit, glance)
  ) %>%
  unnest(tidied)

# Bind all back to a single data frame
df_lm <- bind_rows(df_track_lm, df_field_lm, df_multi_lm)
  
x <- df_lm %>% 
  filter(term == "YEAR_QUAL") %>% 
  filter(p.value < 0.05/84)

x

```

